postgres:
  dsn: "host=localhost user=stech password=stech dbname=foodbar port=5432 sslmode=disable TimeZone=Asia/Jakarta"
halalmui:
  base_url: "http://dev-api.halalmui.org"
  secret_code: "H4l4lMU!"
